server:
  port: 0

spring:
  application:
    name: catalog-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/msa
    username: postgres
    password:
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    lease-renewal-interval-in-seconds: 20 # 20초마다 하트비트 전송
    lease-expiration-duration-in-seconds: 60 # 60초 동안 하트비트 없으면 만료

logging:
  level:
    org.springframework.security: DEBUG