version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:4.1.3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672" # AMQP 프로토콜 포트
      - "15672:15672" # RabbitMQ Management UI 포트
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - ecommerce-network

  # zipkin 서비스 추가
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    environment:
      STORAGE_TYPE: mem # 메모리 저장소로 변경
    networks:
      - ecommerce-network

volumes:
  # 아래 두 볼륨을 명시적으로 정의해주어야 합니다.
  rabbitmq_data:

networks:
  ecommerce-network:
    name: ecommerce-network
    # 외부 네트워크가 아닐 경우, 아래 external: true는 삭제
    external: true