server:
  port: 0

spring:
  application:
    name: user-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:file:~/msadb;DB_CLOSE_DELAY=-1;
#    #url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;
#    username: sa
#    password:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/msa
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create
  security:
    user:
      name: user
      password: $2a$10$dBTMbV.fmURHgNMEKfH6see8ezKWJmjqMoAK8U5vIaLmTLgQlBiwe

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    lease-renewal-interval-in-seconds: 20 # 20초마다 하트비트 전송
    lease-expiration-duration-in-seconds: 60 # 60초 동안 하트비트 없으면 만료

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health
          - beans
          - info
          - busrefresh
  tracing:
    sampling:
      probability: 1.0 # 추적할 요청의 샘플링 확률 (0.0 ~ 1.0).
      # 1.0은 모든 요청을 추적하며, 개발 단계에서 유용합니다.
      # 0.1은 10%의 요청만 추적합니다.
    enabled: true # 트레이싱 기능 활성화 (기본값은 true)
  zipkin:
    tracing:
      # Zipkin 서버의 API 엔드포인트 주소입니다.
      # Docker로 Zipkin을 실행했을 경우 기본 주소입니다.
      endpoint: http://localhost:9411

logging:
  level:
    com.example.user_service.client: DEBUG
#    root: DEBUG
#    # 특정 패키지 (예: user-service의 컨트롤러가 있는 패키지)
#    com.example.user_service: DEBUG