server:
  port: 0

spring:
  application:
    name: user-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
  security:
    user:
      name: user
      password: $2a$10$dBTMbV.fmURHgNMEKfH6see8ezKWJmjqMoAK8U5vIaLmTLgQlBiwe

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    lease-renewal-interval-in-seconds: 20 # 20초마다 하트비트 전송
    lease-expiration-duration-in-seconds: 60 # 60초 동안 하트비트 없으면 만료

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health
          - beans
          - info
          - busrefresh

logging:
  level:
    com.example.user_service.client: DEBUG
#    root: DEBUG
#    # 특정 패키지 (예: user-service의 컨트롤러가 있는 패키지)
#    com.example.user_service: DEBUG