server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - RewritePath=/(?<serviceName>.*?)/(?<segment>.*), /${segment}
            - name: GlobalFilter
              args:
                baseMessage: Spring Cloud Gateway WebFlux Global Filter
                preLogger: true
                postLogger: true
          routes:
            - id: user-service-without-auth
              uri: lb://USER-SERVICE
              predicates:
#                  - Path=/user-service/{segment:h2-console|login}
                - Path=/user-service/{segment:login}
              filters:
                  - RemoveRequestHeader=Cookie
            - id: user-service-with-auth
              uri: lb://USER-SERVICE
              predicates:
                - Path=/user-service/**
              filters:
                - RemoveRequestHeader=Cookie
                - AuthorizationHeaderFilter
            - id: catalog-service
              uri: lb://CATALOG-SERVICE
              predicates:
                - Path=/catalog-service/**
            - id: order-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/order-service/**

logging:
  level:
    # Spring Cloud Gateway의 라우팅 관련 로그
    org.springframework.cloud.gateway: DEBUG
    # 로드 밸런서 관련 로그 (Netflix Ribbon 또는 Spring Cloud LoadBalancer)
    org.springframework.cloud.loadbalancer: DEBUG
    reactor.netty: DEBUG # 네트워크 관련 상세 로그
    # 서비스 디스커버리 클라이언트 (Eureka) 관련 로그
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health
          - beans
          - info
          - httpexchanges
          - busrefresh